### ISSUE TITLE
Home video titles visible

### ISSUE THREAD

**Issue by ChiaraGambone** [peabrainiac/youtube-recommendation-blocker#1]
I'm not sure if it's the new Firefox 71.0 or the new add-on version 1.0.3 but I now see video titles in the home screen.

![immagine](https://user-images.githubusercontent.com/31727137/70329047-c4f85400-183a-11ea-9bf7-e5c42ae642f7.png)

I do not see these video titles when I have a video open and the suggested videos are hidden by the add-on.

**Comment by peabrainiac** [comment]
Yup, looks like youtube changed how the video titles are set up recently.
Version 1.0.4 should fix that issue though.
